### ISSUE TITLE
Image Rotation

### ISSUE THREAD

**Issue by bodeg** [jamesmontemagno/app-compass#2]
I think the  arrow image rotation should be bind to -1 * Heading

**Comment by akoranteng** [comment]
I am getting error running the source code provided on your Github link. The solution only compiles after commenting out line#49 and line#51
Also when I rotate the device, the compass location is not updat
![Screen Shot 2021-09-27_MyCompass](https://user-images.githubusercontent.com/13998322/135000677-1c84270f-6a07-4194-9700-9b0f2744bbb3.png)
e

**Comment by jamesmontemagno** [comment]
Updated source code
